import { mat4, quat, vec3 } from 'gl-matrix';
import { Node } from './base/node';
import type { SkeletonData, SkeletonAnimClip, IKChain, IKKeyframeTrack, SkeletonPose, SpringChain, SpringCollider } from '../../types/armature-3d';

/**
 * Skeleton3D — scene-graph node that owns a joint hierarchy.
 *
 * After any joint rotation/position change call computeWorldMatrices()
 * to rebuild both joint world matrices and the flattened skinMatrices
 * array (skinMatrix[i] = worldMatrix[i] × inverseBindMatrix[i]).
 * The renderer reads skinMatrices directly from this node.
 */
export class Skeleton3D extends Node {
  public id: string = crypto.randomUUID();
  public data: SkeletonData;
  /**
   * Flat skin-matrix array: data.joints.length × 16 floats.
   * Each entry is skinMatrix[i] = worldMatrix[i] × inverseBindMatrix[i].
   * Written by computeWorldMatrices(); read by Renderer3D each frame.
   */
  public skinMatrices: Float32Array;
  /** Set to true by computeWorldMatrices(); cleared by the renderer after upload. */
  public matricesDirty = true;

  /**
   * The skeleton's OBJECT transform (a character's move/rotate/scale), applied to the root joint in
   * computeWorldMatrices so it propagates to every joint → skinning AND bones follow it together.
   * Identity by default (so existing skeletons are unchanged); synced from the body mesh's transform
   * by Scene3DManager. See docs/specs/character-transform-on-skeleton.md.
   */
  public objectTransform: Float32Array = mat4.create() as Float32Array;

  /**
   * True when this skeleton was generated by the procedural body generator (createProceduralBody3D).
   * Its mesh ships pre-rigged with generator weights, so the armature panel should hide "Bind Mesh"
   * (re-binding would clobber those weights). Persisted via toJSON/fromJSON so it survives reload.
   */
  public isProceduralBody = false;

  constructor(data: SkeletonData) {
    super();
    this.data = data;
    this.skinMatrices = new Float32Array(data.joints.length * 16);
    this.computeWorldMatrices();
  }

  /**
   * Recompute world matrices for all joints (parent-first order assumed),
   * then update the flat skinMatrices array.
   */
  computeWorldMatrices(): void {
    const { joints } = this.data;
    const local = mat4.create() as Float32Array;
    const tmp   = mat4.create() as Float32Array;

    for (const j of joints) {
      const rot   = (j.constraintRotation ?? j.ikRotation ?? j.localRotation) as unknown as quat;
      const scale = (j.constraintScale ?? j.localScale) as unknown as vec3;
      mat4.fromRotationTranslationScale(
        local as unknown as mat4,
        rot,
        j.localPosition as unknown as vec3,
        scale,
      );

      if (j.parentIndex < 0) {
        // Apply the skeleton NODE's own transform (the character's object transform) to the root, so it
        // propagates to every joint → skinning AND bones follow it together. Identity node transform
        // (the default for all existing skeletons) leaves this unchanged. See
        // docs/specs/character-transform-on-skeleton.md.
        mat4.mul(
          j.worldMatrix as unknown as mat4,
          this.objectTransform as unknown as mat4,
          local as unknown as mat4,
        );
      } else {
        mat4.mul(
          j.worldMatrix as unknown as mat4,
          joints[j.parentIndex].worldMatrix as unknown as mat4,
          local as unknown as mat4,
        );
      }

      // skinMatrix = worldMatrix × inverseBindMatrix
      mat4.mul(
        tmp as unknown as mat4,
        j.worldMatrix as unknown as mat4,
        j.inverseBindMatrix as unknown as mat4,
      );
      this.skinMatrices.set(tmp, j.index * 16);
    }
    this.matricesDirty = true;
  }

  /** Override one joint's local rotation (quaternion xyzw) and recompute. */
  setJointRotation(jointIndex: number, q: [number, number, number, number]): void {
    if (jointIndex < 0 || jointIndex >= this.data.joints.length) return;
    this.data.joints[jointIndex].localRotation = q;
    this.computeWorldMatrices();
  }

  /** Override one joint's local position and recompute. */
  setJointPosition(jointIndex: number, p: [number, number, number]): void {
    if (jointIndex < 0 || jointIndex >= this.data.joints.length) return;
    this.data.joints[jointIndex].localPosition = p;
    this.computeWorldMatrices();
  }

  // ── Joint authoring ───────────────────────────────────────────────────────

  /**
   * Append a new joint as a child of `parentIndex` (-1 = root).
   * Returns the new joint's index.
   */
  addJoint(parentIndex: number, localPos: [number, number, number], name?: string): number {
    const { joints } = this.data;
    const idx = joints.length;
    joints.push({
      index: idx,
      name: name ?? `joint_${idx}`,
      parentIndex,
      children: [],
      localPosition: [...localPos] as [number, number, number],
      localRotation: [0, 0, 0, 1],
      localScale: [1, 1, 1],
      tailOffset: [0, 0.3, 0],
      worldMatrix: new Float32Array(16),
      inverseBindMatrix: new Float32Array(16),
    });
    if (parentIndex >= 0 && parentIndex < joints.length - 1) {
      joints[parentIndex].children.push(idx);
    }
    // Grow skinMatrices
    const newSkin = new Float32Array(joints.length * 16);
    newSkin.set(this.skinMatrices);
    this.skinMatrices = newSkin;
    this.computeWorldMatrices();
    return idx;
  }

  /**
   * Remove joint at `jointIndex` and all its descendants.
   * Re-indexes remaining joints so indices stay contiguous.
   */
  removeJoint(jointIndex: number): void {
    const { joints } = this.data;
    if (jointIndex < 0 || jointIndex >= joints.length) return;

    // Collect joint + descendants
    const toRemove = new Set<number>();
    const stack = [jointIndex];
    while (stack.length) {
      const ji = stack.pop()!;
      toRemove.add(ji);
      for (const c of joints[ji].children) stack.push(c);
    }

    // Build old→new index map for survivors
    const oldToNew = new Array<number>(joints.length).fill(-1);
    let ni = 0;
    for (let i = 0; i < joints.length; i++) {
      if (!toRemove.has(i)) oldToNew[i] = ni++;
    }

    const newJoints = joints
      .filter((_, i) => !toRemove.has(i))
      .map(j => ({
        ...j,
        index: oldToNew[j.index],
        parentIndex: j.parentIndex < 0 ? -1 : oldToNew[j.parentIndex],
        children: j.children.filter(c => !toRemove.has(c)).map(c => oldToNew[c]),
      }));

    this.data.joints = newJoints;
    this.skinMatrices = new Float32Array(newJoints.length * 16);
    this.computeWorldMatrices();
  }

  /**
   * Drop all joints with index >= `count` (the TRAILING joints) — e.g. spring-bone tail joints appended
   * after the base rig. Safe because trailing joints have the highest indices, so removing them leaves every
   * lower (body) index unchanged — no re-indexing of mesh joint references (unlike removeJoint). Prunes
   * dangling child links and shrinks skinMatrices. No-op when count >= the current joint count.
   */
  truncateJoints(count: number): void {
    if (count < 0 || count >= this.data.joints.length) return;
    this.data.joints.length = count;
    for (const j of this.data.joints) j.children = j.children.filter(c => c < count);
    this.skinMatrices = new Float32Array(count * 16);
    this.computeWorldMatrices();
  }

  /** Move a joint's local position without changing parent or children. */
  moveJoint(jointIndex: number, localPos: [number, number, number]): void {
    if (jointIndex < 0 || jointIndex >= this.data.joints.length) return;
    this.data.joints[jointIndex].localPosition = [...localPos] as [number, number, number];
    this.computeWorldMatrices();
  }

  /** Rename a joint. */
  renameJoint(jointIndex: number, name: string): void {
    if (jointIndex < 0 || jointIndex >= this.data.joints.length) return;
    this.data.joints[jointIndex].name = name;
  }

  /** Set the visual tail offset (in the joint's own local frame). Leaf joints use
   *  this to draw the diamond-stick tip and the draggable tail handle sphere. */
  setJointTailOffset(jointIndex: number, offset: [number, number, number]): void {
    if (jointIndex < 0 || jointIndex >= this.data.joints.length) return;
    this.data.joints[jointIndex].tailOffset = [...offset] as [number, number, number];
  }

  /** Recompute inverseBindMatrix for all joints from their current worldMatrix. */
  computeInverseBindMatrices(): void {
    for (const j of this.data.joints) {
      mat4.invert(j.inverseBindMatrix as unknown as mat4, j.worldMatrix as unknown as mat4);
    }
  }

  /** Clear all per-frame IK rotations, reverting joints to their FK localRotation. */
  clearIKRotations(): void {
    for (const j of this.data.joints) {
      j.ikRotation = undefined;
    }
  }

  toJSON(): any {
    return {
      ...super.toJSON(),
      type: 'Skeleton3D',
      id: this.id,
      ...(this.isProceduralBody ? { isProceduralBody: true } : {}),
      skeletonData: {
        name: this.data.name,
        joints: this.data.joints.map(j => ({
          index:             j.index,
          name:              j.name,
          parentIndex:       j.parentIndex,
          children:          [...j.children],
          localPosition:     [...j.localPosition],
          localRotation:     [...j.localRotation],
          localScale:        [...j.localScale],
          tailOffset:        [...j.tailOffset],
          inverseBindMatrix: Array.from(j.inverseBindMatrix),
          // ikRotation/constraintRotation/constraintScale intentionally omitted — ephemeral
          ...(j.constraints?.length ? { constraints: j.constraints } : {}),
        })),
        clips: (this.data.clips ?? []).map(c => ({
          id:         c.id,
          name:       c.name,
          startFrame: c.startFrame,
          endFrame:   c.endFrame,
          fps:        c.fps,
          tracks:     c.tracks,
          ...(c.ikTracks && c.ikTracks.length > 0 ? { ikTracks: c.ikTracks } : {}),
        })),
        ikChains: (this.data.ikChains ?? []).map(ch => ({
          id:          ch.id,
          endJointIdx: ch.endJointIdx,
          chainLength: ch.chainLength,
          target:      [...ch.target] as [number, number, number],
          ...(ch.poleTarget ? { poleTarget: [...ch.poleTarget] as [number, number, number] } : {}),
          blendWeight: ch.blendWeight ?? 1,
          enabled:     ch.enabled,
        })),
        poses: (this.data.poses ?? []).map(p => ({ ...p })),
        ...(this.data.springChains?.length
          ? { springChains: this.data.springChains.map(s => ({ ...s, jointIndices: [...s.jointIndices], gravityDir: [...s.gravityDir] as [number, number, number] })) }
          : {}),
        ...(this.data.springColliders?.length
          ? { springColliders: this.data.springColliders.map(c => ({ jointIdx: c.jointIdx, offset: [...c.offset] as [number, number, number], radius: c.radius, ...(c.tail ? { tail: [...c.tail] as [number, number, number] } : {}) })) }
          : {}),
      },
    };
  }

  /** Reconstruct a Skeleton3D from JSON produced by toJSON(). */
  static fromJSON(data: any): Skeleton3D {
    const joints: import('../../types/armature-3d').Joint3D[] = (data.skeletonData?.joints ?? []).map((j: any) => ({
      index:             j.index,
      name:              j.name ?? `joint_${j.index}`,
      parentIndex:       j.parentIndex ?? -1,
      children:          j.children ?? [],
      localPosition:     j.localPosition ?? [0, 0, 0],
      localRotation:     j.localRotation ?? [0, 0, 0, 1],
      localScale:        j.localScale ?? [1, 1, 1],
      tailOffset:        j.tailOffset ?? [0, 0.3, 0],
      worldMatrix:       new Float32Array(16),
      inverseBindMatrix: new Float32Array(j.inverseBindMatrix ?? new Array(16).fill(0)),
      ...(j.constraints?.length ? { constraints: j.constraints } : {}),
    }));
    const clips: SkeletonAnimClip[] = (data.skeletonData?.clips ?? []).map((c: any) => ({
      id:         c.id ?? crypto.randomUUID(),
      name:       c.name ?? 'clip',
      startFrame: c.startFrame ?? 0,
      endFrame:   c.endFrame ?? 24,
      fps:        c.fps ?? 24,
      tracks:     c.tracks ?? [],
      ...(c.ikTracks && c.ikTracks.length > 0
        ? { ikTracks: (c.ikTracks as any[]).map((t: any): IKKeyframeTrack => ({
              chainId:   t.chainId ?? '',
              property:  t.property ?? 'target',
              keyframes: t.keyframes ?? [],
            })) }
        : {}),
    }));
    const ikChains: IKChain[] = (data.skeletonData?.ikChains ?? []).map((ch: any) => ({
      id:          ch.id ?? crypto.randomUUID(),
      endJointIdx: ch.endJointIdx ?? 0,
      chainLength: ch.chainLength ?? 2,
      target:      ch.target ?? [0, 0, 0],
      ...(ch.poleTarget ? { poleTarget: ch.poleTarget as [number, number, number] } : {}),
      blendWeight: ch.blendWeight ?? 1,
      enabled:     ch.enabled ?? true,
    }));
    const poses: SkeletonPose[] = (data.skeletonData?.poses ?? []).map((p: any) => ({
      id:        p.id,
      name:      p.name,
      rotations: p.rotations,
    }));
    const springChains: SpringChain[] = (data.skeletonData?.springChains ?? []).map((s: any) => ({
      id:           s.id ?? crypto.randomUUID(),
      jointIndices: s.jointIndices ?? [],
      stiffness:    s.stiffness ?? 0.5,
      drag:         s.drag ?? 0.4,
      gravity:      s.gravity ?? 0.003,
      gravityDir:   s.gravityDir ?? [0, -1, 0],
      hitRadius:    s.hitRadius ?? 0.01,
      enabled:      s.enabled ?? true,
    }));
    const springColliders: SpringCollider[] = (data.skeletonData?.springColliders ?? []).map((c: any) => ({
      jointIdx: c.jointIdx ?? 0,
      offset:   c.offset ?? [0, 0, 0],
      radius:   c.radius ?? 0.05,
      ...(c.tail ? { tail: c.tail as [number, number, number] } : {}),
    }));
    const skel = new Skeleton3D({ name: data.skeletonData?.name ?? 'skeleton', joints, clips, ikChains, poses, springChains, springColliders });
    if (data.id) skel.id = data.id;
    if (data.isProceduralBody) skel.isProceduralBody = true;
    skel.name = data.name ?? '';
    return skel;
  }
}
